import Head from 'next/head';
import Link from 'next/link';

const PostsIndex = () => {
  return (
    <>
      <Head>
        <title>Posts</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Link href='/pre/posts'>
        <h2 className='m-auto font-bold'>Posts</h2>
      </Link>
      <Link href='/pre/products'>
        <h2 className='m-auto font-bold'>Products</h2>
      </Link>
    </>
  );
};

export default PostsIndex;
